name: Archive artifacts
description: Uploads artifacts produced during a workflow run to S3
inputs:
  branch:
    description: "The name of the branch to pull artifacts for"
    default: ${{ github.head_ref || github.ref_name }}
runs:
  using: "composite"
  steps:
    - name: "Authenticate to artifact storage"
      uses: digirati-co-uk/digirati-ops-actions/.github/actions/aws-login@main

    - run: |
        aws s3 cp --recursive s3://digirati-ci-artifacts/digirati-co-uk/$REPOSITORY/$BRANCH/ artifacts/*
      env:
        REPOSITORY: ${{ github.event.repository.name }}
        BRANCH: ${{ inputs.branch }}
      shell: bash