name: AWS Login
description: "Authenticate to AWS using ambient OIDC credentials from GH actions. Requires id_token: write permissions"
outputs:
  url:
    description: "Base URL of assets available on CloudFront"
    value: ${{ steps.upload.outputs.url }}
inputs:
  prefix:
    default: ${{ github.head_ref || github.ref_name }}
    description: The path under S3 that the artifacts are uploaded to. Defaults to the branch name.

runs:
  using: "composite"
  steps:
    - name: "Authenticate to artifact storage"
      uses: catnekaise/cognito-idpool-auth@main
      with:
        auth-flow: "enhanced"
        cognito-identity-pool-id: "eu-west-1:48b1e5ba-eed1-47f9-b45e-a4b27a2798c3"
        aws-account-id: "144289631794"
        aws-region: "eu-west-1"
        set-in-environment: true
