name: Query for image by app_version and tag
description: "TODO"

inputs:
  step_name:
    description: 'The name of the step executing this action, used for the summary'
    required: false
    default: 'Image Query'
  repository_name:
    description: 'ECR repository name'
    required: true
  app_version:
    description: 'App version tag to be included in image as APP_VERSION env variable.'
    required: true

outputs:
  exists:
    description: Whether an image tagged with app_version already exists.
    value: ${{ steps.query-images.outputs.exists }}

runs:
  using: "composite"
  steps:
    - name: Querying ${{ inputs.repository_name }} for ${{ inputs.app_version }}
      id: query-images
      shell: bash
      run: |
        echo "::notice::Querying ${{ inputs.repository_name }} for ${{ inputs.app_version }}"
        IMAGE_METADATA=$(aws ecr describe-images \
          --repository-name "${{ inputs.repository_name }}" \
          --image-ids imageTag="${{ inputs.app_version }}" \
          --output json 2>/dev/null || echo "NOT_FOUND")

        echo "IMAGE_METADATA = $IMAGE_METADATA"
        echo "## ${{ inputs.step_name }}" >> $GITHUB_STEP_SUMMARY
        echo "| Repository | Version | Found | Tags |" >> $GITHUB_STEP_SUMMARY
        echo "| :--- | :--- | :--- | :--- |" >> $GITHUB_STEP_SUMMARY
        if [ "$IMAGE_METADATA" != "NOT_FOUND" ] && echo "$IMAGE_METADATA" | jq -e '.imageDetails[0].imageDigest' >/dev/null 2>&1; then
          IMAGE_TAGS=$(echo "$IMAGE_METADATA" | jq -r '.imageDetails[0].imageTags[]?' | paste -sd "," -)
          echo "::notice::Image found in ECR with tag ${{inputs.app_version}}."
           echo "| ${{inputs.repository_name}} | ${{ inputs.app_version}} | True | $IMAGE_TAGS |" >> $GITHUB_STEP_SUMMARY
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "::notice::Image not found in ECR: ${{inputs.app_version}}."
          echo "| ${{inputs.repository_name}} | ${{ inputs.app_version}} | False | |" >> $GITHUB_STEP_SUMMARY
          echo "exists=false" >> $GITHUB_OUTPUT
        fi