name: Archive artifacts
description: Uploads artifacts produced during a workflow run to S3
outputs:
  url:
    description: "Base URL of assets available on CloudFront"
    value: ${{ steps.upload.outputs.url }}
inputs:
  prefix:
    default: ${{ github.head_ref || github.ref_name }}
    description: The path under S3 that the artifacts are uploaded to. Defaults to the branch name.

runs:
  using: "composite"
  steps:
    - name: "Authenticate to artifact storage"
      uses: digirati-co-uk/digirati-ops-actions/.github/actions/aws-login@main

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - run: |
        aws s3 cp --recursive artifacts/* s3://digirati-ci-artifacts/$ORG/$REPOSITORY/$PREFIX/
        echo "url=https://d1o8q7gs2alph4.cloudfront.net/$ORG/$REPOSITORY/$PREFIX/index.html" >> $GITHUB_OUTPUT
      id: upload
      env:
        ORG: ${{ github.repository_owner }}
        REPOSITORY: ${{ github.event.repository.name }}
        PREFIX: ${{ inputs.prefix }}
      shell: bash
