name: Archive artifacts
description: Uploads artifacts produced during a workflow run to S3
runs:
  using: "composite"
  steps:
    - name: "Authenticate to artifact storage"
      uses: catnekaise/cognito-idpool-auth@main
      with:
        auth-flow: "enhanced"
        cognito-identity-pool-id: "eu-west-1:48b1e5ba-eed1-47f9-b45e-a4b27a2798c3"
        aws-account-id: "144289631794"
        aws-region: "eu-west-1"
        set-in-environment: true

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true

    - run: |
        aws s3 cp --recursive artifacts/* s3://digirati-ci-artifacts/digirati-co-uk/$REPOSITORY/$BRANCH/
      env:
        REPOSITORY: ${{ github.event.repository.name }}
        BRANCH: ${{ github.head_ref || github.ref_name }} 
      shell: bash