name: Get Deployed Version
description: "Gets the version of the image from the currently deployed environment. If a deployment url is provided, it will retrieve the version from that url. Otherwise, it will skip this step."
inputs:
  version_url:
    description: "Url to retrieve the current_version version"
    required: false
    default: ""
outputs:
  deployed_version:
    description: The currently deployed version
    value: ${{ steps.get-deployed-version.outputs.version || 'Not Detected' }}

runs:
  using: composite
  steps:
    - name: Get currently deployed version.
      shell: bash
      if: ${{inputs.version_url != ''}}
      id: get-deployed-version
      run: |
        DEPLOYED_VERSION=$(curl -s "${{inputs.version_url}}" | jq -r ".version")
        echo "::notice::Got version $DEPLOYED_VERSION from ${{inputs.version_url}}"
        echo "version=${DEPLOYED_VERSION}" >> $GITHUB_OUTPUT
    - name: Deployed Version Summary
      shell: bash
      id: version-summary
      run: |
        if [ -n "${{ steps.get-deployed-version.outputs.version }}" ]; then
          DEPLOYED_VAL="\`${{ steps.get-deployed-version.outputs.version }}\`"
          DEPLOYED_SOURCE_VAL="${{ inputs.version_url }}"
        else
          DEPLOYED_VAL="*Skipped*"
          DEPLOYED_SOURCE_VAL="*N/A*"
        fi
        echo "## Deployed Version" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Version Type | Source | Value |" >> $GITHUB_STEP_SUMMARY
        echo "| :--- | :--- | :--- |" >> $GITHUB_STEP_SUMMARY
        echo "| **Deployed Version** | $DEPLOYED_SOURCE_VAL | $DEPLOYED_VAL |" >> $GITHUB_STEP_SUMMARY