name: Run ecs task.
description: "TODO"

inputs:
  step_name:
    description: 'The name of the step executing this action, used for the summary'
    required: false
    default: 'Management Task'
  ecs_cluster:
    description: 'The name of the target ECS Cluster'
    required: true
  management_task_definition:
    description: 'Management task definition'
    required: true
  management_service:
    description: 'Management service'
    required: true
  image_version:
    description: 'sha- form of image tag.'
    required: true
  command:
    description: 'Command array to run in management task, formatted as a JSON array string'
    required: true
    default: '["manage.py"]'
  log_prefix:
    description: 'Log prefix to query management task logs.'
    required: true
  force_recreate:
    description: Recreate the management task definition for the deployed version if exists.
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Query for existing management task definition
      shell: bash
      if: ${{ inputs.force_recreate == 'false' }}
      id: query-management-task-def
      run: |
        echo "Querying for Task Definition: ${{inputs.management_task_definition}} tagged with ${{inputs.image_version}}"
        TAGGED_TASK_DEFS=$(aws resourcegroupstaggingapi get-resources \
          --resource-type-filters "ecs:task-definition" \
          --tag-filters "Key=ImageVersion,Values=${{inputs.image_version}}" \
          --output json)
          echo "TAGGED_TASK_DEFS = $TAGGED_TASK_DEFS"
        EXISTING_ARN=$(echo "$TAGGED_TASK_DEFS" | jq -r \
          --arg family "/${{inputs.management_task_definition}}:" \
          '.ResourceTagMappingList[].ResourceARN | select(contains($family))' | \
          sort -V | tail -n 1)
        if [ -n "$EXISTING_ARN" ] && [ "$EXISTING_ARN" != "null" ]; then
          echo "::notice::Task Definition found: $EXISTING_ARN"
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "arn=$EXISTING_ARN" >> $GITHUB_OUTPUT
        else
          echo "::notice::No existing Task Definition."
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Create template management task definition
      shell: bash
      if: |
        steps.query-management-task-def.outputs.exists == 'false' ||
        steps.query-management-task-def.outputs.exists == '' ||
        inputs.force_recreate == 'true'
      id: get-template-management-task-def
      run: |
        aws ecs describe-task-definition \
          --task-definition ${{ inputs.management_task_definition }} \
          --query taskDefinition > management-task-def.json

        cat management-task-def.json | jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' > template-management-task-def.json
        echo "template=template-management-task-def.json" >> $GITHUB_OUTPUT

    - name: Login to Amazon ECR
      if: |
        steps.query-management-task-def.outputs.exists == 'false' ||
        steps.query-management-task-def.outputs.exists == '' ||
        inputs.force_recreate == 'true'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Render Deployed Management Task Definition
      if: |
        steps.query-management-task-def.outputs.exists == 'false' ||
        steps.query-management-task-def.outputs.exists == '' ||
        inputs.force_recreate == 'true'
      id: render-management-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{steps.get-template-management-task-def.outputs.template}}
        container-name: ${{ inputs.management_service}}
        image: ${{ steps.login-ecr.outputs.registry }}/ch-monet/letters-backend:${{
          inputs.image_version }}

    - name: Register new task definition revision.
      shell: bash
      if: |
        steps.query-management-task-def.outputs.exists == 'false' ||
        steps.query-management-task-def.outputs.exists == '' ||
        inputs.force_recreate == 'true'
      id: register-management-task-def
      run: |
        NEW_ARN=$(aws ecs register-task-definition \
          --cli-input-json file://${{steps.render-management-task-def.outputs.task-definition}} \
          --tags key=ImageVersion,value="${{inputs.image_version}}" \
          --query "taskDefinition.taskDefinitionArn" \
          --output text)
        echo "::notice:: Registered new task definition: $NEW_ARN" 
        echo "arn=$NEW_ARN" >> $GITHUB_OUTPUT

    - name: Run Task Summary
      shell: bash
      run: |
        echo "## ${{ inputs.step_name }}" >> $GITHUB_STEP_SUMMARY
        echo "| Cluster | Task Definition | Service | Image Version | Command | Log Prefix |" >> $GITHUB_STEP_SUMMARY
        echo "| :--- | :--- | :--- | :--- | :--- | :--- |" >> $GITHUB_STEP_SUMMARY
        echo "| ${{inputs.ecs_cluster}} | ${{inputs.management_task_definition}} | ${{inputs.management_service}} | ${{inputs.image_version}} | \`${{inputs.command}}\` | ${{inputs.log_prefix}} |" >> $GITHUB_STEP_SUMMARY
